services:
  web:
    build: .
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - .:/app
      - media:/app/media
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      DATABASE_URL: postgres://wagtail:wagtail@db:5432/wagtail
    depends_on:
      - db
    command: bash -lc "cd /app && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: wagtail
      POSTGRES_USER: wagtail
      POSTGRES_PASSWORD: wagtail
    volumes:
      - pgdata:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  media:
  staticfiles:
  pgadmin_data:
