# Generated by Django 5.1.15 on 2026-03-09 06:20

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(default='À propos', max_length=100)),
                ('about_text', wagtail.fields.RichTextField(blank=True, default='Kerenes est un projet collaboratif visant à valoriser les talents et l’innovation au Congo.')),
                ('links_title', models.CharField(default='Liens utiles', max_length=100)),
                ('links', wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('link_page', 1), ('link_url', 2)]], {})}, default=[])),
                ('social_title', models.CharField(default='Suivez-nous', max_length=100)),
                ('socials', wagtail.fields.StreamField([('social', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Nom du réseau (Facebook, X/Twitter, LinkedIn…)', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Classe Bootstrap Icons (ex: bi bi-facebook)', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('icon_class', 1), ('url', 2)]], {})}, default=[])),
                ('footer_bg_class', models.CharField(default='bg-navy', help_text='Classe CSS de fond (ex: bg-navy ou bg-dark)', max_length=100)),
                ('footer_text_class', models.CharField(default='text-light', help_text='Classe CSS du texte (ex: text-light)', max_length=100)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Footer (paramètres du site)',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('link_url', models.CharField(blank=True, help_text='Choisissez une page interne ou renseignez une URL externe ou relative.', max_length=255)),
                ('show_children', models.BooleanField(default=True)),
                ('visibility', models.CharField(choices=[('all', 'Toujours visible'), ('auth', 'Visible si connecté'), ('anon', 'Visible si non connecté')], default='all', help_text="Contrôle l'affichage selon l'état de connexion", max_length=10)),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.menu')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('link_url', models.CharField(blank=True, help_text='Choisissez une page interne ou renseignez une URL externe ou relative.', max_length=255)),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
