# Generated by Django 5.1.15 on 2026-03-13 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0004_delete_momoaccesstoken_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomoAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('api_user', models.CharField(max_length=255)),
                ('target_env', models.CharField(default='sandbox', max_length=50)),
                ('access_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('bank', 'Virement bancaire'), ('mobile', 'Mobile money'), ('card', 'Carte')], max_length=10)),
                ('status', models.CharField(choices=[('initiated', 'Initié'), ('pending', 'En attente'), ('confirmed', 'Confirmé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='initiated', max_length=12)),
                ('provider', models.CharField(blank=True, choices=[('mtn_cg', 'MTN Congo')], max_length=20)),
                ('payer_phone', models.CharField(blank=True, max_length=30)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('external_id', models.CharField(blank=True, max_length=80)),
                ('provider_status', models.CharField(blank=True, max_length=80)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('dues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.memberannualdues')),
            ],
        ),
    ]
