# Generated by Django 5.1.15 on 2026-03-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Genre'),
        ),
    ]
