# Generated by Django 5.1.15 on 2026-02-25 10:57

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_footersettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footersettings',
            options={'verbose_name': 'Footer (paramètres du site)'},
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='body',
        ),
        migrations.AddField(
            model_name='footersettings',
            name='about_text',
            field=wagtail.fields.RichTextField(blank=True, default='Kerenes est un projet collaboratif visant à valoriser les talents et l’innovation au Congo.'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='about_title',
            field=models.CharField(default='À propos', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='footer_bg_class',
            field=models.CharField(default='bg-navy', help_text='Classe CSS de fond (ex: bg-navy ou bg-dark)', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='footer_text_class',
            field=models.CharField(default='text-light', help_text='Classe CSS du texte (ex: text-light)', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='links',
            field=wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texte du lien', 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Lien vers une page interne', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': '…ou URL externe', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('url', 2)]], {})}, default=[]),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='links_title',
            field=models.CharField(default='Liens utiles', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='social_title',
            field=models.CharField(default='Suivez-nous', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='socials',
            field=wagtail.fields.StreamField([('social', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Nom du réseau (Facebook, X/Twitter, LinkedIn…)', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Classe Bootstrap Icons (ex: bi bi-facebook)', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('icon_class', 1), ('url', 2)]], {})}, default=[]),
        ),
    ]
