# Generated by Django 5.1.15 on 2026-02-25 12:32

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_footersettings_options_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_alt', models.CharField(blank=True, max_length=160)),
                ('show_toc', models.BooleanField(default=True, help_text='Afficher le sommaire automatique (H2)')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('paragraphe', 0), ('image', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'bold', 'italic', 'link', 'ol', 'ul']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
