# Generated by Django 5.1.15 on 2026-03-04 20:54

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_standardpage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='editorial_body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='editorial_title',
            field=models.CharField(blank=True, default='Editorial', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='latest_articles_count',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='homepage',
            name='latest_articles_title',
            field=models.CharField(blank=True, default='Articles', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='perspectives_excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='perspectives_page',
            field=models.ForeignKey(blank=True, help_text="Choisir la page rubrique 'Regards d’ingénieurs' (ou équivalent).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='perspectives_title',
            field=models.CharField(blank=True, default='Regards d’ingénieurs', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_latest_articles',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='spotlight_page',
            field=models.ForeignKey(blank=True, help_text='Choisir une page profil/ingénieur à mettre en avant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='spotlight_title',
            field=models.CharField(blank=True, default='Un ingénieur, un impact', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tagline',
            field=models.CharField(blank=True, help_text='Ex: « L’ingénieur au cœur du développement du Congo »', max_length=255),
        ),
        migrations.CreateModel(
            name='HomeHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('cta_text', models.CharField(blank=True, default='En savoir plus', max_length=50)),
                ('cta_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeQuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=80)),
                ('text', models.TextField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_links', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
