# Generated by Django 5.1.15 on 2026-03-08 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_editorial_body_homepage_editorial_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Laisser vide pour un lien de premier niveau.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link_url',
            field=models.CharField(blank=True, help_text='Choisissez une page interne ou renseignez une URL externe.', max_length=255),
        ),
        migrations.DeleteModel(
            name='SubMenuItem',
        ),
    ]
