# Generated by Django 5.1.15 on 2026-03-08 15:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_menu_items_alter_footersettings_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='items',
            field=wagtail.fields.StreamField([('item', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Choisissez une page interne ou renseignez une URL externe ou relative.', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('all', 'Toujours visible'), ('auth', 'Visible si connecté'), ('anon', 'Visible si non connecté')]}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('link_page', 1), ('link_url', 2)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Sous-liens', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('link_page', 1), ('link_url', 2), ('show_children', 3), ('visibility', 4), ('children', 6)]], {})}, verbose_name='Éléments du menu'),
        ),
    ]
