# Generated by Django 5.1.15 on 2026-03-09 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_footersettings_id_alter_footertext_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='site',
        ),
        migrations.DeleteModel(
            name='FooterText',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='FooterSettings',
        ),
    ]
