server {
  listen 80;
  server_name oic.cg www.oic.cg 51.255.196.187;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location /media/ {
    alias /app/media/;
  }

  location /static/ {
    alias /app/staticfiles/;
  }

  location / {
    proxy_pass http://web:8000;

    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
