# Generated by Django 5.1.15 on 2026-03-08 07:47

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='XAF', max_length=10)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrgChartPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='OrgSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMenuFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no', models.CharField(max_length=30, unique=True)),
                ('is_active_member', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberAnnualDues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('due', 'À payer'), ('partial', 'Partiel'), ('paid', 'Payé')], default='due', max_length=10)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_dues', to='members.annualfee')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to='members.memberprofile')),
            ],
            options={
                'unique_together': {('member', 'fee')},
            },
        ),
        migrations.CreateModel(
            name='OrgChartSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='members.orgchartpage')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='members.orgsection')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrgChartSectionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='members.member')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='members.orgchartsection')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('bank', 'Virement bancaire'), ('mobile', 'Mobile money'), ('card', 'Carte')], max_length=10)),
                ('status', models.CharField(choices=[('initiated', 'Initié'), ('pending', 'En attente'), ('confirmed', 'Confirmé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='initiated', max_length=12)),
                ('provider', models.CharField(blank=True, choices=[('mtn_cg', 'MTN Congo')], max_length=20)),
                ('payer_phone', models.CharField(blank=True, max_length=30)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('external_id', models.CharField(blank=True, max_length=80)),
                ('provider_status', models.CharField(blank=True, max_length=80)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('dues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.memberannualdues')),
            ],
        ),
        migrations.CreateModel(
            name='UserMenuFragmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=255)),
                ('only_staff', models.BooleanField(default=False, help_text='Visible uniquement pour staff/admin')),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('fragment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='members.usermenufragment')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
