# Generated by Django 5.1.15 on 2026-03-05 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthMenuSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_admin_link', models.BooleanField(default=True)),
                ('admin_label', models.CharField(default='Administration', max_length=50)),
                ('dues_label', models.CharField(default='Mes cotisations', max_length=50)),
                ('dues_url', models.CharField(default='/me/cotisations/', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
