# Generated by Django 5.1.15 on 2026-03-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_momoaccesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momoaccesstoken',
            name='provider',
            field=models.CharField(max_length=50),
        ),
    ]
