# Generated by Django 5.1.15 on 2026-03-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_momoaccesstoken_provider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MomoAccessToken',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
