# Generated by Django 5.1.15 on 2026-03-05 14:24

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_delete_authmenusettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMenuFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserMenuFragmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=255)),
                ('only_staff', models.BooleanField(default=False, help_text='Visible uniquement pour staff/admin')),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('fragment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='members.usermenufragment')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
